version: "3"

services:
  langbot:
    image: registry.cn-hangzhou.aliyuncs.com/junyang/lang_bot:latest
    container_name: langbot
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 5300:5300  # 供 WebUI 使用
      - 2280-2290:2280-2290  # 供消息平台适配器方向连接
    # 根据具体环境配置网络
